### ISSUE TITLE
Update source data

### ISSUE THREAD

**Issue by petri** [Gawaboumga/iso-20275-python#1]
Looks like this library includes an outdated copy of data from gleif.org. Could we please incorporate the latest one? 

If this package included a script that runs the necessary cleanups (those that can be automatic) on the source CSV, contributors could run that and then submit updated files in PR.

**Comment by Gawaboumga** [comment]
I've updated the version; the 0.0.4 should now be disponible.
I was not expecting someone to use my module =)

**Comment by petri** [comment]
Thanks. See https://github.com/psolin/cleanco ...
