### ISSUE TITLE
missing csv files on package

### ISSUE THREAD

**Issue by giacodp** [Gawaboumga/iso-20275-python#14]
Hi,
maybe it's a well known issue. I tried to install this package by pypi (pip install iso20275), but there aren't the newest csv files. The latest one I have is ISO-20275 - 2019-11-06.csv, but as I understood I should have ISO-20275 - 2020-11-19.csv.
Can we except the upload in the near future?
Thank you

**Comment by Gawaboumga** [comment]
Hello,

I finally understood why there was a problem between the files available in my package and the one available on pip. I updated (after several tries) and it should work now !

So you just need to update to your version to 0.0.16 and beyond !

**Comment by giacodp** [comment]
It works!
Thank you
